---

- name: create python dev env
  user: root
  hosts: localhost

  tasks:
    - name: Upgrading all packages (CentOS)
      yum:
        name: '*'
        state: latest

    - name: install htop, screen
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - htop
        - screen

  roles:
    - user
    - git
    - terminator
    - vim
    - i3
    - python
