

- name: install i3
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - i3 
    - i3status 
    - dmenu 
    - i3lock 
    - xbacklight 
    - feh 
    - conky


- file:
    path: "/home/{{target_user}}/.config"
    state: directory
    mode: 0644

- file:
    path: "/home/{{target_user}}/.config/i3"
    state: directory
    mode: 0644

- template:
    src: config.j2
    dest: "/home/{{target_user}}/.config/i3/confg"
    owner: "{{target_user}}"
    group: "{{target_user}}"
    mode: 0644

