
- name: install terminator
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - terminator

- file:
    path: "/home/{{target_user}}/.config"
    state: directory
    owner: "{{target_user}}"
    group: "{{target_user}}"
    mode: 0644

- file:
    path: "/home/{{target_user}}/.config/terminator"
    state: directory
    owner: "{{target_user}}"
    group: "{{target_user}}"
    mode: 0644

- template:
    src: config.j2
    dest: "/home/{{target_user}}/.config/terminator/confg"
    owner: "{{target_user}}"
    group: "{{target_user}}"
    mode: 0644

