
- name: install vim
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim

- template:
    src: vimrc.j2
    dest: "/home/{{target_user}}/.vimrc"
    owner: "{{target_user}}"
    group: "{{target_user}}"
    mode: 0644

- git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: "/home/{{target_user}}/.vim/bundle/Vundle.vim"

- file:
    path: "/home/{{target_user}}/.vim"
    owner: "{{target_user}}"
    group: "{{target_user}}"
    recurse: yes
    mode: 0755


    #- shell: "sudo -u {{target_user}} vim +PluginInstall +qall"
